name: Build KrbRelayUp - test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Restore NuGet packages
      run: nuget restore KrbRelayUp.sln

    - name: Build solution
      run: msbuild /p:Configuration=Release /p:Platform="Any CPU" KrbRelayUp.sln
      
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: KrbRelayUp
        path: KrbRelayUp/bin/Release/KrbRelayUp.exe